def create_pdf_report(name, age, problem, roast_text):
    pdf = FPDF()
    pdf.add_page()
    
    def clean(t):
        return str(t).encode('latin-1', 'ignore').decode('latin-1')

    # PAGE 1: THE ANALYSIS
    pdf.set_font("Helvetica", 'B', 22)
    pdf.cell(0, 20, f"{clean(name).upper()}'S UPGRADE PLAN", ln=True, align='C') # [cite: 1]
    
    # Section: Vibe Check
    pdf.ln(10)
    pdf.set_font("Helvetica", 'B', 14)
    pdf.cell(0, 10, "THE VIBE CHECK:", ln=True) # [cite: 2]
    pdf.set_font("Helvetica", size=11)
    pdf.multi_cell(0, 7, txt=clean(roast_text))
    
    # Section: Expanded Deep Scan
    pdf.ln(10)
    pdf.set_font("Helvetica", 'B', 14)
    pdf.cell(0, 10, f"DEEP SCAN: {clean(problem).upper()}", ln=True) # [cite: 6]
    pdf.set_font("Helvetica", size=11)
    
    # Расширенный текст Deep Scan (динамически дополняется)
    deep_scan_expanded = (
        f"The pronounced state of {problem} on your face suggests your skin has been engaging in a "
        "long-term relationship with environmental stress. Those creases and textures look like a "
        "roadmap to every late night and skipped SPF application. We are seeing significant loss "
        "of structural integrity that requires immediate intervention before it becomes permanent."
    ) # [cite: 7, 9]
    pdf.multi_cell(0, 7, txt=clean(deep_scan_expanded))

    # NEW: Also Detected Section
    pdf.ln(8)
    pdf.set_font("Helvetica", 'B', 12)
    pdf.set_text_color(150, 0, 0)
    pdf.cell(0, 10, "ALSO DETECTED (NOT INCLUDED IN THIS REPORT):", ln=True) # 
    pdf.set_font("Helvetica", 'I', 11)
    pdf.set_text_color(0, 0, 0)
    # Здесь перечисляем проблемы, которые НЕ были выбраны основной целью
    pdf.cell(0, 7, "- Significant lack of deep hydration", ln=True) # 
    pdf.cell(0, 7, "- Visible loss of skin elasticity", ln=True) # 
    pdf.cell(0, 7, "- Uneven skin tone and micro-inflammation", ln=True) # 
    pdf.set_font("Helvetica", size=10)
    pdf.cell(0, 7, "(Note: User can analyze these separately for a full recovery.)", ln=True)

    # PAGE 2: PROTOCOLS
    pdf.add_page()
    pdf.set_font("Helvetica", 'B', 16)
    pdf.cell(0, 10, "CLINICAL PROTOCOL (PRO LEVEL)", ln=True) # [cite: 13]
    pdf.set_font("Helvetica", size=10)
    pdf.multi_cell(0, 6, txt="Consult a certified doctor before these treatments.") # [cite: 14, 50]
    
    pro_treatments = [
        ("Botox Injections", "Relaxes muscles to reduce appearance of wrinkles."), # [cite: 15, 16]
        ("Biorevitalization", "Hydrates deeply to restore suppleness."), # [cite: 17, 18]
        ("RF-Lifting", "Tightens skin and reduces fine lines.") # [cite: 19, 20]
    ]
    for treat, target in pro_treatments:
        pdf.set_font("Helvetica", 'B', 11)
        pdf.cell(0, 7, f"[*] {treat}", ln=True)
        pdf.set_font("Helvetica", size=10)
        pdf.cell(0, 5, f"Target: {target}", ln=True)
        pdf.ln(2)

    # PAGE 3: DAILY OPS & UPSELL
    pdf.add_page()
    pdf.set_font("Helvetica", 'B', 14)
    pdf.cell(0, 10, "DAILY OPERATIONS", ln=True) # [cite: 33]
    pdf.set_font("Helvetica", size=10)
    pdf.multi_cell(0, 6, txt="AM: Cleanse -> Vit C Serum -> Peptide Moisturizer -> SPF 30+.\nPM: Cleanse -> Retinol -> Rich Cream.") # [cite: 34, 38, 39, 42]

    # Final Bro Roast & Upsell
    pdf.ln(15)
    pdf.set_fill_color(240, 240, 240)
    pdf.set_font("Helvetica", 'B', 12)
    pdf.cell(0, 10, "A FINAL WORD FROM DR. ROAST:", ln=True, fill=True) # [cite: 44]
    pdf.set_font("Helvetica", 'I', 11)
    
    final_joke = (
        f"Listen, {name}, you can find the active substances in any pharmacy, but since I am "
        "saving for a house in Lake Oswego and a car, I'm offering you the easy way out."
    ) # [cite: 45, 46]
    pdf.multi_cell(0, 7, txt=clean(final_joke))

    # THE UPSELL BUTTON LOGIC
    pdf.ln(10)
    pdf.set_text_color(200, 0, 0)
    pdf.set_font("Helvetica", 'B', 14)
    pdf.cell(0, 10, ">>> GET THE READY-MADE SHOPPING LIST ($5) <<<", ln=True, align='C', link="https://skin-roast.lemonsqueezy.com/upsell") # [cite: 48]
    pdf.set_text_color(0, 0, 0)
    pdf.set_font("Helvetica", size=9)
    pdf.cell(0, 7, "(Stop wasting time and let me pick the brands for you.)", ln=True, align='C')

    # Medical Disclaimer
    pdf.ln(10)
    pdf.set_font("Helvetica", size=8)
    pdf.set_text_color(120, 120, 120)
    pdf.multi_cell(0, 5, txt="MEDICAL DISCLAIMER: Generated by AI. Informational only. Not medical advice.") # [cite: 49, 50]

    with tempfile.NamedTemporaryFile(delete=False, suffix=".pdf") as tmp:
        pdf.output(tmp.name)
        return tmp.name
